name: coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install golang
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: generate cover profile
        run: go test -coverprofile=coverage.out -covermode=atomic
      - name: upload cover profile to codecov
        uses: codecov/codecov-action@v3
